version: '3.8'

services:
  app:
    container_name: eva-app
    restart: always
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - ${PORT}:${PORT}
    depends_on:
      - db
    networks:
      - eva-network
    environment:
      DATABASE_URL: postgresql://user:password@db:5432/database_name

  db:
    container_name: eva-postgres
    restart: always
    build:
      context: .
      dockerfile: Dockerfile.postgres
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: database_name
    networks:
      - eva-network
    ports:
      - '5432:5432'
    volumes:
      - postgres:/var/lib/postgresql/data

volumes:
  postgres:

networks:
  eva-network:
    driver: bridge
