# Использовать официальный образ PostgreSQL
FROM postgres:13.5-alpine

# Установить переменные окружения для PostgreSQL
ENV POSTGRES_USER=user
ENV POSTGRES_PASSWORD=password
ENV POSTGRES_DB=database_name