version: '3.8'
services:
  app:
    build: .
    ports:
      - '4000:4000'
    depends_on:
      - db
    environment:
      DATABASE_URL: postgresql://user:password@db:5432/database_name
  db:
    image: postgres:13.5
    volumes:
      - postgres:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: database_name
    ports:
      - '5432:5432'
volumes:
  postgres: